### ISSUE TITLE
Filter which images/containers should be cached

### ISSUE THREAD

**Issue by behcio** [ScribeMD/docker-cache#532]
While I love the action and use it in our CI projects, I'm a bit concerned if it isn't "overzealous" with caching images.
Allow me to show a few examples of my concern. All snippets are part of a docker compose `yml` file.
1. Container (`service` in the yml file) has the following property: `image: some/dockerimage:latest`. Will the `docker-cache` action always see it as a cache-hit scenario, even if `dockerimage:latest` is updated.
2. Container does NOT have the `image` property, but instead `build` with context and args etc. Generally, it builds an image straight from codebase (repo). Will such container be ever considered for caching?

These 2 concerns got me thinking that perhaps an option to exclude specified service/container names from caching would be a nice feature.
Or perhaps I could just put the step that launches the containers with `build` before the `docker-cache` step?

**Comment by Kurt-von-Laven** [comment]
I moved this issue to the `docker-cache` repository. `docker-cache` doesn't read any of your source files. It considers the cache to have hit if and only if the provided [key](https://github.com/ScribeMD/docker-cache/blob/3072594f8b04431a0b5255ceb3353a6cae3a5ae0/README.md#key) identically matches a key for which you have a cache saved. It currently caches anything listed by [`docker image list --format "{{ .Repository }}:{{ .Tag }}"`](https://github.com/ScribeMD/docker-cache/blob/3072594f8b04431a0b5255ceb3353a6cae3a5ae0/src/docker.ts#L10) that is present during the post step at the end of your job but wasn't present during the main step when you called `docker-cache`. Hence, as you suggested, it should be called after any steps that build or pull Docker images that you don't wish to cache and before any steps that build or pull Docker images that you do want to cache. [The official Docker build push action](https://github.com/docker/build-push-action) performs Docker layer caching, so it is better suited to caching built images. Please let me know if that doesn't address your concerns.

**Comment by Kurt-von-Laven** [comment]
Please feel free to comment if this didn't address your concerns. Tentatively closing this for now.
