### ISSUE TITLE
none tags will cause save to fail

### ISSUE THREAD

**Issue by khivi** [ScribeMD/docker-cache#609]
```
Images present before restore step will be skipped; only new images will be saved.
docker save --output ~/.docker-images.tar ghcr.io/foo/node:<none> ghcr.io/foo/node:latest 
Error: Error: Command failed: docker save --output ~/.docker-images.tar ghcr.io/foo/node:<none> ghcr.io/foo/node:latest 
/usr/bin/bash: line 1: none: No such file or directory

```

**Comment by Kurt-von-Laven** [comment]
Duplicate #572.

**Comment by Kurt-von-Laven** [comment]
Thank you! It occurs to me that we could probably save the anonymous images by ID and the names ones by name to avoid the need for a feature flag.

**Comment by Kurt-von-Laven** [comment]
@khivi, I have implemented said strategy adding support for untagged images in #816. I added a test case for an image without a name, but I wonder if you might know how to create an image without a tag using the Docker CLI?
