### ISSUE TITLE
Node version mismatch

### ISSUE THREAD

**Issue by alexkuc** [ScribeMD/docker-cache#613]
There is a mismatch between the node version specified in `package.json` and the actual node version when used as a part of GitHub workflow:

https://github.com/ScribeMD/docker-cache/blob/8cd7495f37b9e168dc6461e56ca302c4e8f6ddfd/package.json#L17-L20

https://github.com/ScribeMD/docker-cache/blob/8cd7495f37b9e168dc6461e56ca302c4e8f6ddfd/action.yaml#L23-L27

**Comment by Kurt-von-Laven** [comment]
Please correct me if I am wrong, but I don't believe that GitHub Actions yet supports `using: node18`. We have never encountered any issues as a consequence of this intentional discrepancy, and I would expect them to be caught in CI. Using the latest LTS version in `package.json` effectively allows us to test against both Node.js 16 and 18, reducing the risk that code is introduced that breaks once GitHub Actions does support Node.js 18. Please let me know if I may have overlooked some drawback of this admittedly counterintuitive decision.

**Comment by alexkuc** [comment]
Oh, I see. You are targeting Node v18 specifically to support it when GitHub Actions support it. Our internal repo actually targets Node v16 and when trying to add this repo (b/c it is not published as npm package), we've run into some issues. In #612 you've mentioned that perhaps GHCR is better suited for our needs so I'll proceed to close this issue and resume conversation there.

**Comment by Kurt-von-Laven** [comment]
Yep, although it's not something I feel strongly about in such a small repository, so we are open to changing the Node.js version in `package.json` in the future. Thank you for alerting us to this issue in any case. If I understand correctly, the issues you encountered would only apply to those attempting to use docker-cache from a JavaScript action, not as a GitHub Action? If so, it sounds like we need to remember to drop the Node.js version to 16 in `package.json` if there is more interest in using docker-cache as an npm package, but it's safe to leave it for now?

**Comment by alexkuc** [comment]
> If I understand correctly, the issues you encountered would only apply to those attempting to use docker-cache from a JavaScript action, not as a GitHub Action?

Yup, that's what I was initially thinking to do.

> If so, it sounds like we need to remember to drop the Node.js version to 16 in `package.json` if there is more interest in using docker-cache as an npm package, but it's safe to leave it for now?

Yeah, safe to leave for now. As mentioned in https://github.com/ScribeMD/docker-cache/issues/612#issuecomment-1684284304, using `docker save` and `docker load` did not lead to better performance so I've decided to leave it as it is for now and come back to the issue of time later.
