### ISSUE TITLE
Use with self-hosted runners?

### ISSUE THREAD

**Issue by randomm** [ScribeMD/docker-cache#696]
I am using self-hosted runners via https://github.com/actions/actions-runner-controller and have bumped into this issue:

```
##[debug]Failed to delete archive: Error: ENOENT: no such file or directory, unlink ''
Recording preexisting Docker images. These include standard images pre-cached by GitHub Actions when Docker is run as root.
docker image list --format "{{ .Repository }}:{{ .Tag }}"
Error: Error: spawn /usr/bin/bash ENOENT
```

Is use of this a no-no with self-hosted runners?

**Comment by Kurt-von-Laven** [comment]
Does your runner have Bash?

**Comment by Galaf** [comment]
I have the same issue unfortunately.
It would be great to be able to set the path to the shell we want.

The command would still work regardless probably.

**Comment by Galaf** [comment]
@Kurt-von-Laven Would it be possible to change shell by setting the `$SHELL` environment variable, maybe?
