### ISSUE TITLE
Add cache-from and cache-to options

### ISSUE THREAD

**Issue by Xpl0itU** [ScribeMD/docker-cache#820]
I have a workflow that gets triggered whenever I create a tag, however, the created cache only works for that tag, and not other tags or any other run at all, see this SO post for what I mean: https://stackoverflow.com/questions/74113734/share-gha-docker-cache-among-branches

**Comment by Kurt-von-Laven** [comment]
What you are describing is the intentional design decision of caching in GitHub Actions.
