### ISSUE TITLE
[Feature Request] Adding a new input 'ignore-prefix' to ignore images that shouldn't be cached

### ISSUE THREAD

**Issue by abdulrahman-streampay** [ScribeMD/docker-cache#821]
Hey [Kurt-von-Laven](https://github.com/Kurt-von-Laven)! 🎉 

This GitHub Action has saved me a lot of time, thank you for building this!

Through out my usage I've noticed that I was in need of a feature to ignore some docker images to be cached, usually those images are the repo image I build and push to ECR. However, they get picked up because the `test.docker-compose.yml` will always have the same hash value, as our integration testing dependencies don't change through out runs.

My proposal is to add a new input `ignore-prefix` to ignore any images starting with any strings we provide in this input array.
I am willing to work on this feature if you believe it's a great addition to this GitHub Action.

Let me know your thoughts.

Best regards, ❤️

**Comment by Kurt-von-Laven** [comment]
Sorry for the slow reply. My initial question is whether your issue can be addressed in your case by moving the `docker-cache` step after the step that builds and pushes your repo image.

**Comment by abdulrahman-streampay** [comment]
I would agree that reordering the pipeline steps might solve the issue. Let me close this issue for now 👍
