### ISSUE TITLE
Error 429

### ISSUE THREAD

**Issue by y-nk** [ScribeMD/docker-cache#829]
Saving and restoring cache seems to work, but then this happens:

```
ERROR: failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/rust/manifests/sha256:de6e081a4e9c10e70731071cec6f629892da1bbaa24b478a96bdc59060674117: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
------
```

and i have no clue why. Any luck?

**Comment by altbdoor** [comment]
It is mentioned in in the error message.

> Server message: toomanyrequests: You have reached your pull rate limit. 
> You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

The Docker webpage mentions:

> The rate limits of 100 container image requests per six hours for anonymous usage, and 200 container image requests per six hours for free Docker accounts are now in effect. Image requests exceeding these limits will be denied until the six hour window elapses.

Should not be a problem with the library, but rather the CI hitting the limits specified by Docker.
