### ISSUE TITLE
Clarify hashFiles(...) on the README

### ISSUE THREAD

**Issue by linusnorton** [ScribeMD/docker-cache#97]
The README has a key example containing `hashFiles(...)` - what should that path be to capture the docker images? Where do they go by default?

**Comment by Kurt-von-Laven** [comment]
The paths you hash don't capture the Docker images, and it's not possible to have a sensible default since you want any file that specifies which Docker images to pull. In the case of docker-cache itself, that's just `.pre-commit-config.yaml`, because the MegaLinter pre-commit hooks pull the MegaLinter Docker image at the version specified [here](https://github.com/ScribeMD/docker-cache/blob/643b9113a22dbf6fd6cd079824d1edc7dd9030a4/.pre-commit-config.yaml#L29). It's not strictly necessary to use `hashFiles`, although it is exceedingly common. In our case, a more precise cache key would be to extract only the MegaLinter flavor and release from the YAML as that would prevent the cache from being invalidated whenever we bump the versions of other pre-commit hooks (or indeed modify `.pre-commit-config.yaml` in any way whatsoever). Does that make sense?

**Comment by linusnorton** [comment]
Yes, I think so. So if I had a docker-compose.yaml file I would specify that so any time it changed the cache key would change

**Comment by Kurt-von-Laven** [comment]
That sounds right to me, but please let me know if you encounter any difficulties.

**Comment by marc-hb** [comment]
FWIW I found `hashFiles(...)` very confusing, for a long time I wondered whether the triple dot was some special syntax. I suggest switching to `hashFiles(some_directories)`.

BTW I'm trying to use the digest of the (single!) image I'm interested in but it's not going well: #305

**Comment by Kurt-von-Laven** [comment]
I'm not convinced that fewer people will be confused by the nonstandard `some_directories` than by `...`. We could link to the official GitHub docs on [`hashFiles`](https://docs.github.com/en/actions/learn-github-actions/expressions#hashfiles) if you feel that would have been helpful, and also open to other suggestions. My two cents in the future would be to Google something like "hashFiles GitHub Actions" if you find yourself in a similar scenario, but I am acutely aware of how much easier it is to pretend I would have done the right thing when I already knew the answer and am a big fan of time-saving documentation.

**Comment by marc-hb** [comment]
Taking a second look at this, I think the other reason why I misinterpreted the triple dots as some special syntax is the fact that `hashFiles` is mentioned absolutely nowhere in the README.md. This seconds the wrong impression that it's something the user should copy without giving it a thought whereas choosing the argument actually requires some far from negligible effort. This effort deserves IMHO a sentence or two describing it in the `Key:` section of the README.md. I think this  would be enough to solve all the problems @linusnorton and I had. A couple sentences would be bit more verbose than trying to find the "optimal" `hashFiles(argument)` but it would leave zero room for error. It's not like the current README.md is already too long right now!

> I'm not convinced that fewer people will be confused by the nonstandard some_directories than by `...`

`some_directories` is pretty generic and not very helpful either but at least it can't fool the reader like `...` did for me. The [official hashFiles documentation](https://docs.github.com/en/actions/learn-github-actions/expressions#hashfiles)  uses a very vague and IMHO not great `path`. I think any [Unix man page](https://linux.die.net/man/) I ever looked at uses some english word as a placeholder; never triple dots alone.


> We could link to the official GitHub docs on [hashFiles](https://docs.github.com/en/actions/learn-github-actions/expressions#hashfiles) if you feel that would have been helpful,

Yes and that too!

> My two cents in the future would be to Google something like "hashFiles GitHub Actions" if you find yourself in a similar scenario

Totally agree that the README.md shouldn't try to copy/paste the Internet; however a couple sentences of introduction and background go a very long way. The very first time I looked at this README.md it wasn't even clear to me that `hashFiles()` came from Github and not from `docker-cache`!

**Comment by Kurt-von-Laven** [comment]
> Taking a second look at this, I think the other reason why I misinterpreted the triple dots as some special syntax is the fact that hashFiles is mentioned absolutely nowhere in the README.md.

This is true in a literal sense, but the README already includes a link to the official GitHub docs that would have clarified all of the confusions you experienced with `hashFiles` and how to create a key:

> The explicit cache key to ferry to the [official GitHub cache action](https://github.com/marketplace/actions/cache).

**Comment by marc-hb** [comment]
> This is true in a literal sense, but the README already includes a link to the official GitHub docs that would have clarified all of the confusions you experienced with hashFiles and how to create a key:

Totally; it "only"... took more time.

Crafting the perfect README.md balance is a very fine art, thanks for listening and trying in #372
